server:
  port: ${port:3302}
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
data:
  env: NaN
  user:
    username: NaN
    password: NaN